begin;
insert into auth.users(id,email,email_confirmed_at) values ('10000000-0000-4000-8000-000000000098','daily-access@example.invalid',now());
insert into public.lm_staff(user_id,role,permissions) values ('10000000-0000-4000-8000-000000000098','accounts',array['expenses']);
set local role authenticated;
select set_config('request.jwt.claim.sub','620ff01b-a3bb-4c91-9242-43a8ce4a49e4',true);
do $$ declare c uuid;oid uuid;piece uuid;salary uuid;profile uuid;ids jsonb:='{}';row record;before jsonb;after jsonb;preview jsonb;result jsonb;archive uuid;total numeric;begin
 result:=public.lm_save_expense_batch('[{"category":"Studio","description":"Batch one","amount":850.25},{"category":"Courier","description":"Batch two","amount":100.50}]',null,null,null);
 if result->>'count'<>'2' then raise exception 'Batch rows missing';end if;
 if exists(select 1 from jsonb_array_elements(public.lm_workspace()->'expenses') e where e->>'id'=any(array(select jsonb_array_elements_text(result->'ids'))) and (e->>'payment_mode' is not null or e->>'paid_by' is not null or e->>'expense_date'<>(now() at time zone 'Asia/Kolkata')::date::text)) then raise exception 'Optional batch defaults failed';end if;
 total:=jsonb_array_length(public.lm_workspace()->'expenses');
 begin perform public.lm_save_expense_batch('[{"category":"Studio","description":"Valid","amount":20},{"category":"Studio","description":"Invalid","amount":0}]',null,null,null);raise exception 'Invalid row accepted';exception when raise_exception then if sqlerrm<>'Each expense needs a description and a positive amount' then raise;end if;end;
 if jsonb_array_length(public.lm_workspace()->'expenses')<>total then raise exception 'Batch saved partly';end if;
 perform public.lm_save_expense_batch('[{"category":"Studio","description":"Bank transfer","amount":1}]','2026-10-07','Muskan','Bank transfer');
 c:=(public.lm_save_record('customers','{"name":"Delete rollback client"}',null)->>'id')::uuid;ids:=ids||jsonb_build_object('customers',c);
 oid:=(public.lm_save_order(jsonb_build_object('reference','DELETE-ROLLBACK','customer_id',c,'order_date','2026-10-07','due_date','2026-10-15','trials','2 trials','advance_date','2026-10-07'),'[{"name":"Top","quantity":1,"price":2000,"status":"New Order"}]',null,500)->>'id')::uuid;ids:=ids||jsonb_build_object('orders',oid);
 if not exists(select 1 from jsonb_array_elements(public.lm_workspace()->'orders') o where o->>'id'=oid::text and o->>'trials'='2 trials' and o->>'fitting_date' is null) then raise exception 'Manual Trials missing';end if;
 piece:=(public.lm_save_record('studio_pieces','{"name":"Delete piece","kind":"Samples","quantity":1,"status":"New Order"}',null)->>'id')::uuid;ids:=ids||jsonb_build_object('studio_pieces',piece);
 ids:=ids||jsonb_build_object('purchases',(public.lm_save_record('purchases',jsonb_build_object('purchase_date','2026-10-07','vendor','Vendor','item','Organza','category','Fabric','quantity',1,'amount',100,'status','Paid','order_id',oid,'studio_piece_id',piece),null)->>'id')::uuid);
 ids:=ids||jsonb_build_object('expenses',(public.lm_save_record('expenses',jsonb_build_object('expense_date','2026-10-07','description','Courier','category','Courier','amount',10,'payment_mode',null,'order_id',oid),null)->>'id')::uuid);
 ids:=ids||jsonb_build_object('jobs',(public.lm_save_record('jobs',jsonb_build_object('karigar','Tailor','work','Cut','kind','Tailor','studio_piece_id',piece,'given_date','2026-10-07','status','Pending'),null)->>'id')::uuid);
 ids:=ids||jsonb_build_object('tasks',(public.lm_save_record('tasks',jsonb_build_object('title','Linked task','task_date','2026-10-07','customer_id',c,'order_id',oid),null)->>'id')::uuid);
 ids:=ids||jsonb_build_object('events',(public.lm_save_record('events',jsonb_build_object('title','Linked event','event_date','2026-10-07','order_id',oid),null)->>'id')::uuid);
 ids:=ids||jsonb_build_object('alterations',(public.lm_save_record('alterations',jsonb_build_object('order_id',oid,'issue','Fit','received_date','2026-10-07','status','Received'),null)->>'id')::uuid);
 salary:=(public.lm_save_record('salaries','{"staff_name":"Rollback salary","salary":1000,"frequency":"Monthly","period_start":"2026-10-01","period_end":"2026-10-31","deduction":0}',null)->>'id')::uuid;ids:=ids||jsonb_build_object('salaries',salary);
 ids:=ids||jsonb_build_object('salary_payments',(public.lm_save_record('salary_payments',jsonb_build_object('salary_id',salary,'payment_date','2026-10-07','amount',100,'kind','Salary','payment_mode','Cash'),null)->>'id')::uuid);
 profile:=(public.lm_save_record('salary_profiles','{"staff_name":"Rollback profile","amount":100,"frequency":"Weekly"}',null)->>'id')::uuid;ids:=ids||jsonb_build_object('salary_profiles',profile);
 ids:=ids||jsonb_build_object('salary_payouts',(public.lm_save_record('salary_payouts',jsonb_build_object('profile_id',profile,'payment_date','2026-10-07','amount',100,'payment_mode','Cash'),null)->>'id')::uuid);
 ids:=ids||jsonb_build_object('inventory',(public.lm_save_record('inventory','{"sku":"ROLLBACK-DELETE","name":"Thread","quantity":1,"unit":"Pieces","category":"Trims","reorder_level":0,"cost":10}',null)->>'id')::uuid);
 ids:=ids||jsonb_build_object('influencer_marketing',(public.lm_save_marketing('{"influencer_name":"Delete influencer","outfit_name":"Top","collaboration":"Barter","status":"Sent"}',null)->>'id')::uuid);
 for row in select key,value#>>'{}' id from jsonb_each(ids) loop
  before:=public.lm_workspace();preview:=public.lm_delete_preview(row.key,row.id::uuid);
  archive:=(public.lm_delete_record(row.key,row.id::uuid,preview->>'token')->>'archive_id')::uuid;
  if row.key='customers' and ((before->'home'->>'sales')::numeric-(public.lm_workspace()->'home'->>'sales')::numeric<>2000 or (before->'home'->>'collected')::numeric-(public.lm_workspace()->'home'->>'collected')::numeric<>500) then raise exception 'Deletion did not update financial totals';end if;
  if exists(select 1 from jsonb_array_elements(coalesce(public.lm_workspace()->row.key,'[]')) r where r->>'id'=row.id) then raise exception 'Delete failed for %',row.key;end if;
  perform public.lm_restore_record(archive);after:=public.lm_workspace();
  if not exists(select 1 from jsonb_array_elements(coalesce(after->row.key,'[]')) r where r->>'id'=row.id) then raise exception 'Restore failed for %',row.key;end if;
  if before->'home' is distinct from after->'home' then raise exception 'Restore changed totals for %',row.key;end if;
 end loop;
 preview:=public.lm_delete_preview('customers',c);
 if (preview->'counts'->>'orders')::int<>1 or (preview->'counts'->>'order_payments')::int<>1 or (preview->'counts'->>'purchase_payments')::int<>1 then raise exception 'Linked deletion scope incomplete';end if;
 begin perform public.lm_delete_record('customers',c,'stale');raise exception 'Stale confirmation accepted';exception when raise_exception then if sqlerrm<>'This entry changed. Review Delete again before confirming.' then raise;end if;end;
 if has_function_privilege('anon','public.lm_delete_record(text,uuid,text)','execute') then raise exception 'Anonymous delete allowed';end if;
end $$;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000098',true);
do $$ begin
 perform public.lm_save_expense_batch('[{"category":"Studio","description":"Allowed expense","amount":5}]',null,null,'Card');
 begin perform public.lm_deleted_list();raise exception 'Non-owner archive read allowed';exception when insufficient_privilege then null;end;
 begin perform public.lm_delete_preview('expenses',gen_random_uuid());raise exception 'Non-owner delete allowed';exception when insufficient_privilege then null;end;
end $$;
select 'Batch atomicity, optional fields, Trials, deletion/restore across all record types, linked records and owner-only access passed' result;
rollback;
