import test from 'node:test';
import assert from 'node:assert/strict';
import {monthSummary,orderCost,balance,sortOrders,weekRange,monthRange,salaryBalance,productTotal,overallStage,rolePermissions} from '../public/domain.js';
const data={orders:[{id:'a',reference:'A',order_date:'2026-10-01',amount:48000,status:'Cutting',due_date:'2026-10-15'},{id:'b',reference:'B',order_date:'2026-09-30',amount:10000,status:'Delivered',due_date:'2026-10-02'},{id:'c',reference:'C',order_date:'2026-10-02',amount:20000,status:'Cancelled',due_date:null}],order_payments:[{order_id:'a',payment_date:'2026-10-01',amount:12000},{order_id:'a',payment_date:'2026-11-01',amount:18000},{order_id:'a',payment_date:'2026-10-01',amount:999,voided:true},{order_id:'b',payment_date:'2026-10-02',amount:10000}],purchases:[{order_id:'a',purchase_date:'2026-10-03',category:'Fabric',amount:12000,status:'Unpaid'}],expenses:[{order_id:'a',expense_date:'2026-10-04',category:'Tailoring',amount:3000},{expense_date:'2026-10-05',category:'Rent',amount:5000},{expense_date:'2026-09-30',category:'Miscellaneous',amount:100}],salaries:[{id:'s',period_start:'2026-10-01',salary:10000,deduction:1000}],salary_payments:[{salary_id:'s',amount:2000,kind:'Advance'},{salary_id:'s',amount:3000,kind:'Salary'},{salary_id:'s',amount:99,voided:true}],alterations:[{order_id:'a',received_date:'2026-10-04',additional_cost:500,status:'In progress'}]};
test('monthly profit counts each source once, unpaid material costs, and salary obligation rather than payments',()=>{const m=monthSummary(data,'2026-10');assert.equal(m.sales,48000);assert.equal(m.orders,1);assert.equal(m.cashCollected,22000);assert.equal(m.allocatedCollected,30000);assert.equal(m.outstanding,18000);assert.equal(m.totalCost,29500);assert.equal(m.profit,18500);assert.equal(m.costs.salaries,9000);});
test('order gross profit uses only linked direct costs',()=>{const c=orderCost(data,data.orders[0]);assert.equal(c.total,15500);assert.equal(c.profit,32500);assert.equal(balance(data,data.orders[0]),18000);});
test('salary advances reduce balance without charging expense twice',()=>assert.equal(salaryBalance(data,data.salaries[0]),4000));
test('fractional-rupee balances stay payable without floating-point shortfalls',()=>{const d={...data,order_payments:[{order_id:'tiny',amount:0.1}],salary_payments:[{salary_id:'tiny',amount:0.1}]};assert.equal(balance(d,{id:'tiny',amount:0.3}),0.2);assert.equal(salaryBalance(d,{id:'tiny',salary:0.3,deduction:0}),0.2);});
test('Monday week boundaries, leap month, no-sale margin, urgent ordering',()=>{assert.deepEqual(weekRange('2026-10-04'),['2026-09-28','2026-10-04']);assert.deepEqual(monthRange('2028-02'),['2028-02-01','2028-02-29']);assert.equal(monthSummary({...data,orders:[]},'2026-10').margin,null);assert.deepEqual(sortOrders(data.orders).map(o=>o.id),['b','a','c']);});

test('multi-outfit order total and overall stage reflect every garment',()=>{const items=[{quantity:1,price:18500,status:'Ready'},{quantity:1,price:12000,status:'Stitching'},{quantity:1,price:8500,status:'Embroidery / Handwork'}];assert.equal(productTotal(items),39000);assert.equal(overallStage(items),'Stitching');assert.equal(productTotal([{quantity:2,price:12.35}]),24.7);assert.equal(overallStage(items.map(i=>({...i,status:'Delivered'}))),'Delivered');});
test('staff role defaults exclude business totals and production prices',()=>{for(const permissions of Object.values(rolePermissions))assert.ok(!permissions.includes('home'));assert.ok(!rolePermissions.production.includes('payments'));assert.deepEqual(rolePermissions.team,['tasks']);assert.ok(rolePermissions.accounts.includes('payments'));});
