import test from 'node:test';
import assert from 'node:assert/strict';
import {invoiceValues,invoiceHTML} from '../public/invoice.js';
const snapshot={order:{invoice_number:'LM-2026-000042',invoice_date:'2026-10-06',due_date:'2026-10-15',amount:1},client:{name:'A <client>',phone:'9000000000',address:'Line one\nLine two'},items:[{name:'Top',quantity:2,price:1250.25},{name:'Skirt',quantity:1,price:3000}],payments:[{amount:1000},{amount:500},{amount:300,voided:true}]};
test('invoice uses every product and all non-void receipts, including partial payments',()=>{assert.deepEqual(invoiceValues(snapshot),{total:5500.5,paid:1500,balance:4000.5});assert.equal(invoiceValues({...snapshot,payments:[{amount:6000}]}).balance,0);});
test('invoice preserves stored identity and safely fills the approved five-column template',()=>{const html=invoiceHTML(snapshot);assert.match(html,/LM-2026-000042/);assert.match(html,/A &lt;client&gt;/);assert.equal((html.match(/<th>/g)||[]).length,5);assert.match(html,/Top/);assert.match(html,/Skirt/);assert.match(html,/Thank You/);assert.doesNotMatch(html,/Shipping|Made for you/);assert.match(invoiceHTML({...snapshot,client:{...snapshot.client,name:'Updated client'}}),/Updated client/);});
test('optional fitting date and payment details appear only when saved',()=>{const blank={...snapshot,order:{...snapshot.order,fitting_date:null,payment_mode:null},payments:[{amount:100,payment_mode:null},{amount:50,payment_mode:'Other'}]};assert.doesNotMatch(invoiceHTML(blank),/FITTING DATE|Payment Mode:|BANK TRANSFER/);const selected={...blank,order:{...blank.order,fitting_date:'2026-10-10',payment_mode:'Cash'},payments:[{amount:100,payment_mode:'Cash'},{amount:50,payment_mode:'UPI',voided:true}]};const html=invoiceHTML(selected);assert.match(html,/FITTING DATE/);assert.match(html,/10 Oct 2026/);assert.match(html,/Payment Mode: <strong>Cash<\/strong>/);assert.doesNotMatch(html,/UPI|BANK TRANSFER/);});

test('customer invoice includes order number and excludes material, address and production details',()=>{const html=invoiceHTML({...snapshot,order:{...snapshot.order,reference:'CLIENT-108',notes:'Internal secret'},items:snapshot.items.map(i=>({...i,fabric:'SECRET MATERIAL',status:'Internal stage',notes:'Internal note'}))});assert.match(html,/ORDER NO\./);assert.match(html,/CLIENT-108/);assert.match(html,/Paid Amount:/);assert.match(html,/<dt>PAID<\/dt>/);assert.doesNotMatch(html,/SECRET MATERIAL|Internal stage|Internal note|Internal secret|Line one|ADVANCE/);});
