begin;
set local role authenticated;
select set_config('request.jwt.claim.sub','620ff01b-a3bb-4c91-9242-43a8ce4a49e4',true);
do $$ declare before_oct jsonb;before_nov jsonb;after_oct jsonb;pid uuid;purchase uuid;pay uuid;d text;begin
 before_oct=public.lm_month_money('2026-10');before_nov=public.lm_month_money('2026-11');
 pid=(public.lm_save_record('salary_profiles','{"staff_name":"Rollback weekly tailor","amount":12000,"frequency":"Weekly","payment_day":"Saturday"}',null)->>'id')::uuid;
 foreach d in array array['2026-10-03','2026-10-10','2026-10-17','2026-10-24'] loop perform public.lm_save_record('salary_payouts',jsonb_build_object('profile_id',pid,'amount',12000,'payment_date',d,'kind','Salary','payment_mode','Other'),null);end loop;
 after_oct=public.lm_month_money('2026-10');if (after_oct->>'salaries')::numeric-(before_oct->>'salaries')::numeric<>48000 then raise exception 'Four weekly payments did not total 48000';end if;
 pay=(public.lm_save_record('salary_payouts',jsonb_build_object('profile_id',pid,'amount',12000,'payment_date','2026-10-31','kind','Salary'),null)->>'id')::uuid;
 if (public.lm_month_money('2026-10')->>'salaries')::numeric-(before_oct->>'salaries')::numeric<>60000 then raise exception 'Five weekly payments did not total 60000';end if;
 perform public.lm_save_record('salary_payouts',jsonb_build_object('profile_id',pid,'amount',12000,'payment_date','2026-11-07','kind','Salary'),null);
 if (public.lm_month_money('2026-11')->>'salaries')::numeric-(before_nov->>'salaries')::numeric<>12000 then raise exception 'Actual date month failed';end if;
 perform public.lm_save_record('salary_payouts','{"voided":true}',pay);
 if (public.lm_month_money('2026-10')->>'salaries')::numeric-(before_oct->>'salaries')::numeric<>48000 then raise exception 'Void did not update salary totals';end if;
 perform public.lm_save_record('purchases','{"purchase_date":"2026-10-05","vendor":"Rollback","item":"Unpaid fabric","category":"Fabric","quantity":1,"amount":900,"status":"Unpaid"}',null);
 if (public.lm_month_money('2026-10')->>'purchases')::numeric<>(before_oct->>'purchases')::numeric then raise exception 'Unpaid purchase counted as cash out';end if;
 purchase=(public.lm_save_record('purchases','{"purchase_date":"2026-10-05","vendor":"Rollback","item":"Fabric","category":"Fabric","quantity":1,"amount":1000,"status":"Part paid","paid_now":100,"paid_date":"2026-10-05"}',null)->>'id')::uuid;
 if (public.lm_month_money('2026-10')->>'purchases')::numeric-(before_oct->>'purchases')::numeric<>100 then raise exception 'Partial purchase payment incorrect';end if;
 perform public.lm_save_record('purchase_payments',jsonb_build_object('purchase_id',purchase,'amount',200,'payment_date','2026-11-02'),null);
 if (public.lm_month_money('2026-10')->>'purchases')::numeric-(before_oct->>'purchases')::numeric<>100 then raise exception 'Later payment leaked into previous month';end if;
 begin perform public.lm_save_record('purchase_payments',jsonb_build_object('purchase_id',purchase,'amount',900,'payment_date','2026-10-05'),null);raise exception 'Purchase overpayment allowed';exception when raise_exception then if sqlerrm<>'Payment exceeds the remaining purchase balance' then raise;end if;end;
 after_oct=public.lm_month_money('2026-10');if (after_oct->>'net')::numeric<>(after_oct->>'collected')::numeric-(after_oct->>'total_out')::numeric then raise exception 'Net formula failed';end if;
end $$;
reset role;
insert into auth.users(id,email,email_confirmed_at) values('20000000-0000-4000-8000-000000000001','money-account-test@example.invalid',now());
insert into public.lm_staff(user_id,role,permissions) values('20000000-0000-4000-8000-000000000001','accounts',array['payments','expenses','purchases']);
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
do $$ begin begin perform public.lm_month_money('2026-10');raise exception 'Accounts received business totals';exception when insufficient_privilege then null;end;
 if public.lm_workspace() ?| array['salary_profiles','salary_payouts'] then raise exception 'Payroll leaked to unapproved accounts';end if;
 begin perform public.lm_save_record('salary_payouts','{"amount":1,"payment_date":"2026-10-06"}',null);raise exception 'Unauthorized salary payment allowed';exception when insufficient_privilege then null;end;
end $$;
reset role;
select 'Cash totals, recurring weekly pay, actual dates, voids, purchase caps and owner-only overview passed' as result;
rollback;
