begin;
set local role authenticated;
select set_config('request.jwt.claim.sub','620ff01b-a3bb-4c91-9242-43a8ce4a49e4',true);
do $$ declare c uuid;oid uuid;v jsonb;num text;begin
 c=(public.lm_save_record('customers','{"name":"Optional rollback","phone":"9000000000","address":"Original address"}',null)->>'id')::uuid;
 oid=(public.lm_save_order(jsonb_build_object('reference','OPTIONAL-ROLLBACK','customer_id',c,'order_date','2026-10-01','due_date','2026-10-15','fitting_date','','payment_mode',null,'advance_date','2026-10-01'),'[{"name":"Top","quantity":1,"price":2000,"status":"New Order"}]',null,500)->>'id')::uuid;
 v=public.lm_invoice(oid);num=v->'order'->>'invoice_number';
 if v->'order'->>'fitting_date' is not null or v->'order'->>'payment_mode' is not null or v->'payments'->0->>'payment_mode' is not null then raise exception 'Optional blank fields forced';end if;
 if v->'order'->>'invoice_date'<>'2026-10-01' then raise exception 'Invoice date differs from entered order date';end if;
 perform public.lm_save_record('customers','{"name":"Latest client","phone":"9000000001","address":"Latest address"}',c);
 perform public.lm_save_order(jsonb_build_object('reference','OPTIONAL-ROLLBACK','customer_id',c,'order_date','2026-10-02','due_date','2026-10-16','fitting_date','2026-10-10','payment_mode','Cash'),'[{"name":"Updated Top","quantity":2,"price":1500,"status":"New Order"},{"name":"Skirt","quantity":1,"price":2000,"status":"New Order"}]',oid,0);
 v=public.lm_invoice(oid);
 if v->'order'->>'invoice_number'<>num or v->'order'->>'invoice_date'<>'2026-10-02' or v->'order'->>'fitting_date'<>'2026-10-10' or v->'order'->>'due_date'<>'2026-10-16' then raise exception 'Identity/date sync failed';end if;
 if v->'client'->>'name'<>'Latest client' or v->'client'->>'phone'<>'9000000001' or v->'client'->>'address'<>'Latest address' then raise exception 'Client sync failed';end if;
 if (v->'order'->>'amount')::numeric<>5000 or jsonb_array_length(v->'items')<>2 or v->'payments'->0->>'payment_mode'<>'Cash' then raise exception 'Products/payment sync failed';end if;
 perform public.lm_save_order(jsonb_build_object('reference','OPTIONAL-ROLLBACK','customer_id',c,'order_date','2026-10-02','due_date','2026-10-16','fitting_date',null,'payment_mode',null),'[{"name":"Top","quantity":1,"price":5000,"status":"New Order"}]',oid,0);
 v=public.lm_invoice(oid);if v->'order'->>'fitting_date' is not null or v->'payments'->0->>'payment_mode' is not null then raise exception 'Cleared fields remained';end if;
end $$;
select 'Optional fields, client/product/payment/date synchronization and permanent identity passed' result;
rollback;
