// Local-only UI test server. Uses synthetic records and never connects to Supabase.
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {randomUUID} from 'node:crypto';
import {cashMonth} from '../public/wallet.js';
import {today,addDays} from '../public/domain.js';
const day=today(),client=randomUUID(),oid=randomUUID(),root=resolve('public');
const data={staff:[{user_id:'qa-user'}],customers:[{id:client,name:'Preview Client',phone:'9000000000',city:'Jaipur',measurements:'Bust 34 · Waist 28',preferences:'Soft pastels'}],orders:[{id:oid,reference:'LM-124',customer_id:client,customer_name:'Preview Client',order_date:day,due_date:addDays(day,2),payment_due_date:day,product:'Ivory embroidered set',quantity:1,amount:48000,status:'Stitching',assigned_to:'Studio team'},{id:randomUUID(),reference:'LM-123',customer_id:client,order_date:day,due_date:addDays(day,-1),amount:12000,status:'Cutting',product:'Kurta set'}],order_payments:[{id:randomUUID(),order_id:oid,payment_date:day,kind:'Advance',amount:12000,payment_mode:'UPI',voided:false}],purchases:[{id:randomUUID(),purchase_date:day,vendor:'Preview Fabrics',item:'Ivory fabric',category:'Fabric',quantity:4,amount:12000,order_id:oid,status:'Paid'}],expenses:[{id:randomUUID(),expense_date:day,description:'Tailoring',category:'Karigar',amount:3000,paid_by:'Owner',payment_mode:'UPI',order_id:oid}],salaries:[],salary_payments:[],alterations:[],inventory:[]};
data.orders.push(...['Deepa','Ananya','A long client name to check phone wrapping'].map((name,i)=>({id:randomUUID(),reference:'000'+(i+1),customer_name:name,order_date:day,due_date:addDays(day,i+3),fitting_date:addDays(day,i+1),product:'Sample outfit',quantity:1,amount:8000,status:'Stitching'})));
data.order_items=data.orders.map(o=>({id:randomUUID(),order_id:o.id,name:o.product,quantity:o.quantity||1,price:o.amount/(o.quantity||1),status:o.status}));
data.studio_pieces=[{id:randomUUID(),name:'Black Sculpt Top',collection:'THE SCULPT EDIT',kind:'Samples',status:'Stitching',quantity:1,due_date:addDays(day,3)}];data.jobs=[];data.tasks=[{id:randomUUID(),title:'Pick up organza fabric',category:'Fabric pickup',task_date:day,created_by:'owner',assigned_user_id:'owner',done:false}];data.events=[];
data.salary_profiles=[{id:'salary-preview',staff_name:'Master Cutting',amount:12000,frequency:'Weekly',payment_day:'Saturday',active:true}];data.salary_payouts=[{id:randomUUID(),profile_id:'salary-preview',amount:12000,payment_date:day,payment_mode:'Cash',kind:'Salary'}];data.purchase_payments=data.purchases.map(p=>({id:randomUUID(),purchase_id:p.id,amount:p.amount,payment_date:p.purchase_date,payment_mode:'Other'}));
data.orders.forEach((o,i)=>{o.invoice_number='LM-2026-'+String(i+1).padStart(6,'0');o.invoice_date=o.order_date;});
if(process.env.EXPENSE_SHEET_QA){
 data.purchases.push(...Array.from({length:240},(_,i)=>({id:randomUUID(),purchase_date:day,vendor:i%2?'Silk House':'Studio Supplies',item:['Organza','Cotton lining','Packaging','Embroidery thread'][i%4],category:i%2?'Fabric':'Packaging',quantity:i%5+1,amount:500+i*10,status:'Unpaid'})));
 data.expenses.push({id:randomUUID(),expense_date:day,description:'Courier',category:'Courier',amount:850,paid_by:'Muskan',payment_mode:'UPI',status:'Paid'},{id:randomUUID(),expense_date:day,description:'Electricity',category:'Studio',amount:3200,paid_by:'Muskan',payment_mode:'Other',status:'Pending'});
 data.salary_profiles[0].job_role='Master cutter';
}
let role='owner';
const send=(res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(body));};
http.createServer(async(req,res)=>{
 try{
  const u=new URL(req.url,'http://127.0.0.1:3001'),path=u.pathname;
  if(path==='/config.js'){res.writeHead(200,{'Content-Type':'text/javascript'});res.end('window.LM_CONFIG={url:"http://127.0.0.1:3001",key:"local-test"};');return;}
  if(path.startsWith('/auth/')){let raw='';for await(const c of req)raw+=c;if(u.searchParams.get('grant_type')==='password')role=JSON.parse(raw).email.split('@')[0];send(res,200,{access_token:role,refresh_token:role,expires_at:Math.floor(Date.now()/1000)+3600,user:{id:role,email:role+'@local.test'}});return;}
  if(path.startsWith('/rest/')){
   let body={};if(req.method!=='GET'){let raw='';for await(const c of req)raw+=c;body=raw?JSON.parse(raw):{};}
   if(path==='/rest/v1/rpc/lm_set_expense_void'){const row=data[body.p_table].find(r=>r.id===body.p_id);row.voided=body.p_voided;send(res,200,{saved:true,id:row.id});return;}
   if(path==='/rest/v1/rpc/lm_invoice'){const order=data.orders.find(o=>o.id===body.p_order_id);send(res,200,{order,client:data.customers.find(c=>c.id===order.customer_id),items:data.order_items.filter(i=>i.order_id===order.id),payments:data.order_payments.filter(p=>p.order_id===order.id&&!p.voided)});return;}
   if(path==='/rest/v1/rpc/lm_month_money'){send(res,200,cashMonth(data,body.p_month));return;}
   if(path==='/rest/v1/rpc/lm_workspace'){
    const permissions={production:['orders','studio','production','tasks','calendar'],team:['tasks'],accounts:['payments','expenses','purchases']}[role]||[];const can=p=>role==='owner'||permissions.includes(p);let result={profile:{user_id:role,role,name:role==='owner'?'Muskan':role,permissions},people:[{user_id:'owner',name:'Muskan'},{user_id:'team',name:'Studio team'}]};
    if(['orders','clients','payments','calendar','production'].some(can)){result.orders=data.orders.map(o=>{const row={...o};if(!can('payments')){delete row.amount;delete row.paid;delete row.payment_due_date;delete row.payment_mode;}return row;});result.order_items=data.order_items.map(i=>{const row={...i};if(!can('payments'))delete row.price;return row;});}
    for(const [table,permission]of Object.entries({customers:'clients',studio_pieces:'studio',jobs:'production',tasks:'tasks',events:'calendar',order_payments:'payments',expenses:'expenses',purchases:'purchases',salaries:'salaries',salary_payments:'salaries',inventory:'owner',salary_profiles:'salaries',salary_payouts:'salaries',purchase_payments:'purchases'}))if(can(permission))result[table]=data[table];
    if(role==='team')result.tasks=data.tasks.filter(t=>t.assigned_user_id==='team'||t.created_by==='team');
    if(can('home')){result.home={sales:data.orders.reduce((v,o)=>v+o.amount,0),collected:12000,outstanding:48000,costs:15000};result.members=[{user_id:'owner',name:'Muskan',email:'owner@local.test',role:'owner',permissions:[]}];}send(res,200,result);return;
   }
   if(path==='/rest/v1/rpc/lm_set_order_delivery'){const o=data.orders.find(o=>o.id===body.p_id),items=data.order_items.filter(i=>i.order_id===o.id);if(body.p_delivered){if(o.status!=='Delivered'){o.delivery_previous_stages={order_status:o.status,items:Object.fromEntries(items.map(i=>[i.id,i.status]))};items.forEach(i=>{if(i.status!=='Cancelled')i.status='Delivered';});o.status='Delivered';}}else{items.forEach(i=>{if(i.status==='Delivered')i.status=o.delivery_previous_stages?.items?.[i.id]||'Ready';});o.status=o.delivery_previous_stages?.order_status||'Ready';o.delivery_previous_stages=null;}send(res,200,{saved:true});return;}
   if(path==='/rest/v1/rpc/lm_save_record'){const rows=data[body.p_table];let row=body.p_id?rows.find(r=>r.id===body.p_id):{id:randomUUID(),created_by:role};if(body.p_id)Object.assign(row,body.p_body);else{Object.assign(row,body.p_body);rows.push(row);}if(body.p_table==='purchases'&&!body.p_id){const amount=row.status==='Paid'?Number(row.amount):Number(row.paid_now||0);if(amount>0)data.purchase_payments.push({id:randomUUID(),purchase_id:row.id,amount,payment_date:row.paid_date||row.purchase_date,payment_mode:'Other'});}send(res,200,{id:row.id,saved:true});return;}
   if(path==='/rest/v1/rpc/lm_save_order'){let row=body.p_id?data.orders.find(o=>o.id===body.p_id):{id:body.p_order.id||randomUUID()};if(!body.p_id){row.invoice_number='LM-2026-'+String(data.orders.length+1).padStart(6,'0');row.invoice_date=body.p_order.order_date;}Object.assign(row,body.p_order,{amount:body.p_items.reduce((v,i)=>v+i.price*i.quantity,0),status:body.p_items[0].status,customer_name:data.customers.find(c=>c.id===body.p_order.customer_id)?.name});row.invoice_date=body.p_order.order_date;if(body.p_id&&'payment_mode' in body.p_order){const initial=data.order_payments.find(p=>p.order_id===row.id&&p.kind==='Advance'&&!p.voided);if(initial)initial.payment_mode=body.p_order.payment_mode;}if(!body.p_id)data.orders.push(row);data.order_items=data.order_items.filter(i=>i.order_id!==row.id);data.order_items.push(...body.p_items.map(i=>({...i,order_id:row.id})));if(body.p_advance)data.order_payments.push({id:randomUUID(),order_id:row.id,amount:body.p_advance,payment_date:row.advance_date,kind:'Advance',payment_mode:row.payment_mode});send(res,200,{id:row.id,saved:true});return;}
   const name=path.split('/').pop().replace(/^lm_/,''),rows=data[name];if(!rows){send(res,404,{message:'Unknown test table'});return;}
   if(req.method==='GET'){const offset=Number(u.searchParams.get('offset')||0),limit=Number(u.searchParams.get('limit')||500);send(res,200,rows.slice(offset,offset+limit));return;}
   if(req.method==='PATCH'){const id=u.searchParams.get('id')?.slice(3),row=rows.find(r=>r.id===id);Object.assign(row,body);send(res,200,[row]);return;}
   const row={id:randomUUID(),created_at:new Date().toISOString(),...body};rows.push(row);send(res,201,[row]);return;
  }
  const file=resolve(root,'.'+(path==='/'?'/index.html':decodeURIComponent(path)));if(!file.startsWith(root+'/')){res.writeHead(403);res.end();return;}
  const content=await readFile(file);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'}[extname(file)]||'text/plain','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"});res.end(content);
 }catch(err){send(res,500,{message:err.message});}
}).listen(3001,'127.0.0.1',()=>console.log('Synthetic UI test preview: http://127.0.0.1:3001'));
